version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_OWNER}/college-schedule-app:${VERSION}
    container_name: college-schedule-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/college-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
    healthcheck:
      disable: true
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: college-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
